name: routemaster
description: Easy-to-use router that uses Navigator 2.0. URL-based routing, simple navigation of tabs and nested routes. Web, mobile and desktop.
version: 0.8.0
homepage: https://github.com/tomgilder/routemaster

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path: ^1.8.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
